### ISSUE TITLE
[Feature request] support for wireguard

### ISSUE THREAD

**Issue by denics** [multipolygon/esphome-for-watchy#3]
since september 2023 wireguard is an official component of esphome, it would be nice to have it as an option. I am playing with it, but I don't know if I have the necessary knowledge

**Comment by denics** [comment]
Just adding this to `v2-watchy.yaml` file with the right configuration under `config.yaml` allowed me to connect to my WG! Great!

```yaml
wireguard:
  # https://esphome.io/components/wireguard.html
  address: $WG_ADDRESS
  private_key: $WG_PRIVATE
  peer_endpoint: $WG_PEER_ENDPOINT
  peer_public_key: $WG_PEER_PUBLIC_KEY
  peer_port: $WG_PEER_PORT
  peer_allowed_ips: WG_PEER_ALLOWED_IPS
```
